import datetime
import uuid
from typing import Sequence, Literal, Optional, Mapping

from resources.resource_stubs import ResourcesServiceAsync
from src.events.event_stubs import *
from src.timeseries.timeseries_stubs import *
from src.units.units_stubs import *
from src.datasets.dataset_stubs import *
class IdCollection:
    @property
    def id(self)-> int: ...
    def external_id(self)-> str: ...



class AsyncDataHubClient:
    @property
    def timeseries(self) -> TimeSeriesServiceAsync: ...
    @property
    def events(self) -> EventsServiceAsync: ...
    @property
    def resources(self) -> ResourcesServiceAsync: ...
    @property
    def units(self)-> UnitsServiceAsync: ...

    @property
    def datasets(self)-> DatasetsServiceAsync: ...



class RetrieveFilter:
    @property
    def id(self) -> int: ...
    @property
    def external_id(self) -> str: ...
    @property
    def start(self) -> datetime.datetime: ...
    @property
    def end(self) -> datetime.datetime: ...
    @property
    def limit(self) -> int: ...
    @property
    def aggregates(self) -> str: ...
    @property
    def granularity(self) -> str: ...
    @property
    def cursor(self) -> str: ...
    def __init__(
            self,
            ts: TimeSeries| IdCollection,
            start: datetime.datetime| None = None,
            end: datetime.datetime| None = None,
            limit:int | None = None,
            aggregates: str | None = None,
            granularity: str | None = None,
            cursor: str | None = None,
    ): ...





class FieldStr:
    @property
    def set(self)-> str: ...
    @set.setter
    def set(self,value: str): ...
    @property
    def set_null(self)-> bool: ...
    @set_null.setter
    def set_null(self,value: bool): ...

class FieldInt:
    @property
    def set(self)-> int: ...
    @set.setter
    def set(self,value: int): ...
    @property
    def set_null(self)-> bool: ...
    @set_null.setter
    def set_null(self,value: bool): ...

class ListFieldU64:
    @property
    def set(self)->  list[int]: ...
    @set.setter
    def set(self, value: list[int]): ...

    @property
    def add(self)->  list[int]: ...
    @add.setter
    def add(self, value: list[int]): ...

    @property
    def remove(self)->  list[int]: ...
    @remove.setter
    def remove(self, value: list[int]): ...


class MapField:
    @property
    def set(self) -> dict[str,str]: ...

    @set.setter
    def set(self, value: dict[str,str]): ...

    @property
    def add(self) -> dict[str,str]: ...

    @add.setter
    def add(self, value: dict[str,str]): ...
    @property
    def remove(self) -> dict[str,str]: ...

    @remove.setter
    def remove(self, value: list[str]): ...
