"""Datapoint aggregate / granularity / cursor coverage.

Mirrors the (#[ignore]) `src/timeseries/test.rs::test_datapoints`. That Rust test
inserts ~5.18M one-per-second datapoints and validates raw retrieval, daily
aggregates, cursor pagination, and deletion against ClickHouse.

Two flavours live here:

* lightweight tests (run by default) exercise aggregates + granularity + cursor
  against the small ``inserted_data`` fixture (100 daily points), so the binding
  surface is covered in normal CI without the heavy load;
* ``test_datapoints_heavy`` is a faithful port of the Rust test (millions of
  points, three 60s ClickHouse-merge sleeps). It is skipped unless
  ``RUN_HEAVY_DATAPOINTS_TESTS=1`` — the same opt-in pattern as the listen tests.
"""
import math
import os
from time import sleep

import pandas as pd
import pytest

import datahub_sdk
from python_tests.fixtures import *  # noqa: F401,F403


# --------------------------------------------------------------------------- #
# Lightweight — runs by default against the 100-point ``inserted_data`` fixture
# --------------------------------------------------------------------------- #

def test_datapoints_aggregates_daily(sync_client, inserted_data, ts_float):
    rf = datahub_sdk.RetrieveFilter(
        ts=ts_float,
        start=pd.Timestamp("2023-01-01", tz="UTC"),
        end=pd.Timestamp("2023-04-30", tz="UTC"),
        aggregates=["avg", "min", "max"],
        granularity="1d",
    )
    datapoints = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
    assert datapoints

    for dp in datapoints:
        assert dp.average is not None
        assert dp.min is not None
        assert dp.max is not None
        # min <= avg <= max must always hold for an aggregate window.
        assert dp.min <= dp.average <= dp.max


def test_datapoints_limit_and_cursor_exposed(sync_client, inserted_data, ts_float):
    # The cursor/next_cursor surface only paginates when a result set exceeds the
    # server page size, which the 100-point fixture never reaches (real cursor
    # traversal is covered by ``test_datapoints_heavy``). At this scale we verify
    # that ``limit`` caps the result and that a complete small page exposes no
    # further cursor.
    rf = datahub_sdk.RetrieveFilter(
        ts=ts_float,
        start=pd.Timestamp("2023-01-01", tz="UTC"),
        end=pd.Timestamp("2023-05-01", tz="UTC"),
        limit=10,
    )
    page = sync_client.timeseries.retrieve_datapoints(rf)[0]
    assert len(page.get_datapoints()) <= 10

    # Retrieving the whole series fits in one page -> no continuation cursor.
    rf = datahub_sdk.RetrieveFilter(
        ts=ts_float,
        start=pd.Timestamp("2023-01-01", tz="UTC"),
        end=pd.Timestamp("2023-05-01", tz="UTC"),
    )
    page = sync_client.timeseries.retrieve_datapoints(rf)[0]
    assert len(page.get_datapoints()) == 100
    assert page.next_cursor is None


# --------------------------------------------------------------------------- #
# Heavy — faithful port of `test_datapoints`, skipped unless opted in
# --------------------------------------------------------------------------- #

_HEAVY_ENABLED = os.environ.get("RUN_HEAVY_DATAPOINTS_TESTS") == "1"
_RANDOM_VALUES_CSV = os.path.join(
    os.path.dirname(__file__), "..", "resources", "test", "random_values.csv"
)
_NUM_DATAPOINTS = 60 * 24 * 3600  # 5_184_000, one per second over 60 days


def _truncate_10(x: float) -> float:
    # ClickHouse avg() carries rounding error; truncate to 10 decimals to match
    # the Rust test's `truncate_10`.
    multiplier = 10.0 ** 10
    return math.floor(x * multiplier) / multiplier


def _read_values_from_file():
    with open(_RANDOM_VALUES_CSV, "r") as f:
        content = f.read()
    values = [float(s.strip()) for s in content.split(",") if s.strip()]
    assert len(values) == _NUM_DATAPOINTS
    return values


@pytest.mark.skipif(
    not _HEAVY_ENABLED,
    reason="set RUN_HEAVY_DATAPOINTS_TESTS=1 to run the multi-million-point port",
)
def test_datapoints_heavy(sync_client):
    ext_id = "pytest_heavy_datapoints_ts"

    # Clean slate in case a previous run leaked the series.
    sync_client.timeseries.delete([ext_id])

    ts = datahub_sdk.TimeSeries(
        external_id=ext_id,
        name="Py SDK Heavy Datapoints",
        description="Generated by the python sdk heavy datapoints test.",
        unit="celsius",
        value_type="float",
    )
    created = sync_client.timeseries.create([ts])[0]

    try:
        values = _read_values_from_file()
        timestamps = pd.date_range(
            "2025-01-01", periods=_NUM_DATAPOINTS, freq="s", tz="UTC"
        )
        sync_client.timeseries.insert_from_lists(
            timestamps=timestamps, values=values, ts=created
        )

        # Wait for ClickHouse to ingest the insert.
        sleep(60)

        # --- raw retrieval (100k limit), values bounded to [160, 200] ---------
        start = pd.Timestamp("2025-01-01", tz="UTC")
        rf = datahub_sdk.RetrieveFilter(ts=created, start=start, limit=100000)
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 100000
        for dp in dps:
            assert dp.timestamp >= start
            assert 160.0 <= dp.value <= 200.0

        # limit=200 returns exactly 200
        rf = datahub_sdk.RetrieveFilter(ts=created, start=start, limit=200)
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 200

        # one-hour window at full second resolution -> 3600 points
        rf = datahub_sdk.RetrieveFilter(
            ts=created,
            start=pd.Timestamp("2025-01-01T06:00:00", tz="UTC"),
            end=pd.Timestamp("2025-01-01T07:00:00", tz="UTC"),
            limit=3600,
        )
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 3600

        # Wait again for the merge before aggregate queries.
        sleep(60)

        # --- daily aggregates -------------------------------------------------
        rf = datahub_sdk.RetrieveFilter(
            ts=created,
            start=pd.Timestamp("2025-01-01", tz="UTC"),
            end=pd.Timestamp("2025-03-01", tz="UTC"),
            aggregates=["avg", "min", "max"],
            granularity="1d",
        )
        agg = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(agg) == 59

        expected_avgs = {
            pd.Timestamp("2025-01-01", tz="UTC"): 179.4516319444,
            pd.Timestamp("2025-01-22", tz="UTC"): 179.5567939814,
            pd.Timestamp("2025-02-22", tz="UTC"): 179.4659953703,
        }
        for dp in agg:
            expected = expected_avgs.get(pd.Timestamp(dp.timestamp))
            if expected is not None:
                assert _truncate_10(dp.average) == expected

        # --- cursor pagination over the raw series ---------------------------
        _validate_raw_datapoints_with_cursor(sync_client, created)

        # --- deletion --------------------------------------------------------
        delete_after = pd.Timestamp("2025-02-05", tz="UTC")
        delete_filter = datahub_sdk.DeleteFilter(
            ts=created, inclusive_begin=delete_after
        )
        sync_client.timeseries.delete_datapoints([delete_filter])
        sleep(60)

        rf = datahub_sdk.RetrieveFilter(
            ts=created,
            start=pd.Timestamp("2025-01-01T06:00:00", tz="UTC"),
            limit=5000,
        )
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 5000
    finally:
        sync_client.timeseries.delete([ext_id])


def _validate_raw_datapoints_with_cursor(sync_client, ts):
    start = pd.Timestamp("2025-01-01", tz="UTC")
    end = pd.Timestamp("2025-03-01", tz="UTC")
    # limit=0 -> backend default max page (100k)
    rf = datahub_sdk.RetrieveFilter(ts=ts, start=start, end=end, limit=0)
    page = sync_client.timeseries.retrieve_datapoints(rf)[0]
    cursor = page.next_cursor
    assert cursor
    assert len(page.get_datapoints()) == 100000

    while cursor:
        rf = datahub_sdk.RetrieveFilter(
            ts=ts, start=start, end=end, limit=0, cursor=cursor
        )
        page = sync_client.timeseries.retrieve_datapoints(rf)[0]
        dps = page.get_datapoints()
        cursor = page.next_cursor
        if cursor is None:
            # final page total is 97_600 (9_468_000 % 100_000)
            assert len(dps) == 97600
        else:
            assert len(dps) == 100000
