"""Datapoint aggregate / granularity / cursor coverage.

Mirrors the (#[ignore]) `src/timeseries/test.rs::test_datapoints`. That Rust test
inserts ~5.18M one-per-second datapoints and validates raw retrieval, daily
aggregates, cursor pagination, and deletion against ClickHouse.

Two flavours live here:

* lightweight tests (run by default) exercise aggregates + granularity + cursor
  against the small ``inserted_data`` fixture (100 daily points), so the binding
  surface is covered in normal CI without the heavy load;
* ``test_datapoints_heavy`` is a faithful port of the Rust test (millions of
  points, three 60s ClickHouse-merge sleeps). It is skipped unless
  ``RUN_HEAVY_DATAPOINTS_TESTS=1`` — the same opt-in pattern as the listen tests.
"""
import datetime
import math
import os
from time import sleep

import pandas as pd
import pytest

import intellistream_datahub_sdk
from polling import poll_until
from python_tests.fixtures import *  # noqa: F401,F403


# --------------------------------------------------------------------------- #
# Lightweight — runs by default against the 100-point ``inserted_data`` fixture
# --------------------------------------------------------------------------- #

def test_datapoints_aggregates_daily(sync_client, inserted_data, ts_float):
    rf = intellistream_datahub_sdk.RetrieveFilter(
        ts=ts_float,
        start=pd.Timestamp("2023-01-01", tz="UTC"),
        end=pd.Timestamp("2023-04-30", tz="UTC"),
        aggregates=["avg", "min", "max"],
        granularity="1d",
    )
    datapoints = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
    assert datapoints

    for dp in datapoints:
        assert dp.average is not None
        assert dp.min is not None
        assert dp.max is not None
        # min <= avg <= max must always hold for an aggregate window.
        assert dp.min <= dp.average <= dp.max


def test_datapoints_limit_and_cursor_exposed(sync_client, inserted_data, ts_float):
    # The cursor/next_cursor surface only paginates when a result set exceeds the
    # server page size, which the 100-point fixture never reaches (real cursor
    # traversal is covered by ``test_datapoints_heavy``). At this scale we verify
    # that ``limit`` caps the result and that a complete small page exposes no
    # further cursor.
    rf = intellistream_datahub_sdk.RetrieveFilter(
        ts=ts_float,
        start=pd.Timestamp("2023-01-01", tz="UTC"),
        end=pd.Timestamp("2023-05-01", tz="UTC"),
        limit=10,
    )
    page = sync_client.timeseries.retrieve_datapoints(rf)[0]
    assert len(page.get_datapoints()) <= 10

    # Retrieving the whole series fits in one page -> no continuation cursor.
    rf = intellistream_datahub_sdk.RetrieveFilter(
        ts=ts_float,
        start=pd.Timestamp("2023-01-01", tz="UTC"),
        end=pd.Timestamp("2023-05-01", tz="UTC"),
    )
    page = sync_client.timeseries.retrieve_datapoints(rf)[0]
    assert len(page.get_datapoints()) == 100
    assert page.next_cursor is None


# --------------------------------------------------------------------------- #
# Heavy — faithful port of `test_datapoints`, skipped unless opted in
# --------------------------------------------------------------------------- #

_HEAVY_ENABLED = os.environ.get("RUN_HEAVY_DATAPOINTS_TESTS") == "1"
_RANDOM_VALUES_CSV = os.path.join(
    os.path.dirname(__file__), "..", "resources", "test", "random_values.csv"
)
_NUM_DATAPOINTS = 60 * 24 * 3600  # 5_184_000, one per second over 60 days


def _truncate_10(x: float) -> float:
    # ClickHouse avg() carries rounding error; truncate to 10 decimals to match
    # the Rust test's `truncate_10`.
    multiplier = 10.0 ** 10
    return math.floor(x * multiplier) / multiplier


def _read_values_from_file():
    with open(_RANDOM_VALUES_CSV, "r") as f:
        content = f.read()
    values = [float(s.strip()) for s in content.split(",") if s.strip()]
    assert len(values) == _NUM_DATAPOINTS
    return values


@pytest.mark.skipif(
    not _HEAVY_ENABLED,
    reason="set RUN_HEAVY_DATAPOINTS_TESTS=1 to run the multi-million-point port",
)
def test_datapoints_heavy(sync_client):
    ext_id = "pytest_heavy_datapoints_ts"

    # Clean slate in case a previous run leaked the series.
    sync_client.timeseries.delete([ext_id])

    ts = intellistream_datahub_sdk.TimeSeries(
        external_id=ext_id,
        name="Py SDK Heavy Datapoints",
        description="Generated by the python sdk heavy datapoints test.",
        unit="celsius",
        value_type="float",
    )
    created = sync_client.timeseries.create([ts])[0]

    try:
        values = _read_values_from_file()
        timestamps = pd.date_range(
            "2025-01-01", periods=_NUM_DATAPOINTS, freq="s", tz="UTC"
        )
        sync_client.timeseries.insert_from_lists(
            timestamps=timestamps, values=values, ts=created
        )

        # Wait for ClickHouse to ingest the insert.
        sleep(90)

        # --- raw retrieval (100k limit), values bounded to [160, 200] ---------
        start = pd.Timestamp("2025-01-01", tz="UTC")
        rf = intellistream_datahub_sdk.RetrieveFilter(ts=created, start=start, limit=100000)
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 100000
        for dp in dps:
            assert dp.timestamp >= start
            assert 160.0 <= dp.value <= 200.0

        # limit=200 returns exactly 200
        rf = intellistream_datahub_sdk.RetrieveFilter(ts=created, start=start, limit=200)
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 200

        # one-hour window at full second resolution -> 3600 points
        rf = intellistream_datahub_sdk.RetrieveFilter(
            ts=created,
            start=pd.Timestamp("2025-01-01T06:00:00", tz="UTC"),
            end=pd.Timestamp("2025-01-01T07:00:00", tz="UTC"),
            limit=3600,
        )
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 3600

        # Wait again for the merge before aggregate queries.
        sleep(90)

        # --- daily aggregates -------------------------------------------------
        rf = intellistream_datahub_sdk.RetrieveFilter(
            ts=created,
            start=pd.Timestamp("2025-01-01", tz="UTC"),
            end=pd.Timestamp("2025-03-01", tz="UTC"),
            aggregates=["avg", "min", "max"],
            granularity="1d",
        )
        agg = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(agg) == 59

        expected_avgs = {
            pd.Timestamp("2025-01-01", tz="UTC"): 179.4516319444,
            pd.Timestamp("2025-01-22", tz="UTC"): 179.5567939814,
            pd.Timestamp("2025-02-22", tz="UTC"): 179.4659953703,
        }
        for dp in agg:
            expected = expected_avgs.get(pd.Timestamp(dp.timestamp))
            if expected is not None:
                assert _truncate_10(dp.average) == expected

        # --- cursor pagination over the raw series ---------------------------
        _validate_raw_datapoints_with_cursor(sync_client, created)

        # --- deletion --------------------------------------------------------
        delete_after = pd.Timestamp("2025-02-05", tz="UTC")
        delete_filter = intellistream_datahub_sdk.DeleteFilter(
            ts=created, inclusive_begin=delete_after
        )
        sync_client.timeseries.delete_datapoints([delete_filter])
        sleep(90)

        rf = intellistream_datahub_sdk.RetrieveFilter(
            ts=created,
            start=pd.Timestamp("2025-01-01T06:00:00", tz="UTC"),
            limit=5000,
        )
        dps = sync_client.timeseries.retrieve_datapoints(rf)[0].get_datapoints()
        assert len(dps) == 5000
    finally:
        sync_client.timeseries.delete([ext_id])


def _validate_raw_datapoints_with_cursor(sync_client, ts):
    start = pd.Timestamp("2025-01-01", tz="UTC")
    end = pd.Timestamp("2025-03-01", tz="UTC")
    # limit=0 -> backend default max page (100k)
    rf = intellistream_datahub_sdk.RetrieveFilter(ts=ts, start=start, end=end, limit=0)
    page = sync_client.timeseries.retrieve_datapoints(rf)[0]
    cursor = page.next_cursor
    assert cursor
    assert len(page.get_datapoints()) == 100000

    while cursor:
        rf = intellistream_datahub_sdk.RetrieveFilter(
            ts=ts, start=start, end=end, limit=0, cursor=cursor
        )
        page = sync_client.timeseries.retrieve_datapoints(rf)[0]
        dps = page.get_datapoints()
        cursor = page.next_cursor
        if cursor is None:
            # final page total is 97_600 (9_468_000 % 100_000)
            assert len(dps) == 97600
        else:
            assert len(dps) == 100000


# --------------------------------------------------------------------------- #
# Range query — that a window containing a datapoint actually returns it
#
# Separated from the aggregate tests above because it guards a different thing: not
# how points are bucketed, but whether the range read finds them at all. A regression
# here returned an empty list for a point that was demonstrably stored, over a window
# spanning years either side of it, through both the REST SDK and the MCP tool that
# wraps it.
#
# Both tests poll. That is the whole design: the failure they exist to catch looks
# exactly like ingestion lag in a single-shot read, so a bare assertion could always be
# waved away as "ClickHouse hadn't merged yet". Polling the *latest* read first
# establishes that the point is stored and readable, and only then does the range read
# get its own full timeout. If latest can see it and a range spanning it cannot, the
# clock has been given every chance and the query is wrong.
# --------------------------------------------------------------------------- #

RANGE_AT = datetime.datetime(2026, 4, 23, 13, 0, 0, tzinfo=datetime.timezone.utc)
RANGE_VALUE = 42.5


def _points(collections):
    """The datapoints of the first collection a retrieve returned, or ``[]``."""
    if not collections:
        return []
    return collections[0].get_datapoints() or []


def _retrieve_range(client, ts, start, end):
    return _points(
        client.timeseries.retrieve_datapoints(
            intellistream_datahub_sdk.RetrieveFilter(ts=ts, start=start, end=end)
        )
    )


def test_range_query_returns_a_datapoint_that_latest_can_see(sync_client, make_ts):
    """A window containing a stored datapoint must return it.

    The window is deliberately absurd — years either side — so nothing about boundary
    handling, inclusivity or timezone can explain an empty result.
    """
    ts = make_ts()
    sync_client.timeseries.insert_from_lists([RANGE_AT], [RANGE_VALUE], ts)

    # Control: prove the point is stored and readable, and wait for it. If this fails,
    # ingestion is the problem and the range query is not implicated at all.
    latest = poll_until(
        lambda: _points(sync_client.timeseries.retrieve_latest_datapoints([ts])),
        bool,
    )
    assert latest, (
        "the datapoint never became readable through retrieve_latest_datapoints — "
        "ingestion did not land, so this test says nothing about the range query"
    )
    assert latest[0].value == pytest.approx(RANGE_VALUE)

    # The point is in the store. Now the range read gets its own full timeout.
    found = poll_until(
        lambda: _retrieve_range(
            sync_client,
            ts,
            datetime.datetime(2000, 1, 1, tzinfo=datetime.timezone.utc),
            datetime.datetime(2030, 1, 1, tzinfo=datetime.timezone.utc),
        ),
        bool,
    )
    assert found, (
        "a range query spanning 2000-2030 returned nothing for a datapoint that "
        "retrieve_latest_datapoints returns — the point is stored, so this is the range "
        "query failing, not eventual consistency"
    )
    assert found[0].value == pytest.approx(RANGE_VALUE)
    assert found[0].timestamp == RANGE_AT


def test_range_query_excludes_points_outside_the_window(sync_client, make_ts):
    """A window that does not contain the point must return nothing.

    The converse of the test above, and the reason that one cannot be satisfied by a
    query that has quietly stopped narrowing and returns everything it can read.
    """
    ts = make_ts()
    sync_client.timeseries.insert_from_lists([RANGE_AT], [RANGE_VALUE], ts)

    inside = poll_until(
        lambda: _retrieve_range(
            sync_client,
            ts,
            RANGE_AT - datetime.timedelta(hours=1),
            RANGE_AT + datetime.timedelta(hours=1),
        ),
        bool,
    )
    assert inside, "the datapoint never became visible to a range query that contains it"

    outside = _retrieve_range(
        sync_client,
        ts,
        datetime.datetime(2020, 1, 1, tzinfo=datetime.timezone.utc),
        datetime.datetime(2020, 1, 2, tzinfo=datetime.timezone.utc),
    )
    assert not outside, f"a window that excludes the datapoint returned it anyway: {outside}"


def test_range_query_end_is_exclusive(sync_client, make_ts):
    """``end`` is exclusive, so a window ending exactly on the point must not return it.

    Pinned because an off-by-one here is invisible in ordinary use and silently shifts
    every aggregate bucket by one sample.
    """
    ts = make_ts()
    sync_client.timeseries.insert_from_lists([RANGE_AT], [RANGE_VALUE], ts)

    poll_until(
        lambda: _retrieve_range(
            sync_client, ts, RANGE_AT, RANGE_AT + datetime.timedelta(seconds=1)
        ),
        bool,
    )
    inclusive_start = _retrieve_range(
        sync_client, ts, RANGE_AT, RANGE_AT + datetime.timedelta(seconds=1)
    )
    assert inclusive_start, "start is inclusive, so a window opening on the point must return it"

    exclusive_end = _retrieve_range(
        sync_client, ts, RANGE_AT - datetime.timedelta(seconds=1), RANGE_AT
    )
    assert not exclusive_end, (
        f"end is exclusive, so a window closing on the point must not return it: {exclusive_end}"
    )
