/* SPDX-License-Identifier: Apache-2.0 */
/*
 * IntelliStream DataHub SDK — C API.
 *
 * Conventions:
 *  - Handles (datahub_config, datahub_client, datahub_listener, datahub_message,
 *    datahub_timeseries) are opaque. Each has a matching _free (or _close) and must not be
 *    released any other way.
 *  - Strings are NUL-terminated UTF-8. Input strings are borrowed for the duration of the call.
 *    A `char **` out-parameter hands the caller an owned string, released with
 *    datahub_string_free(); a `const char *` returned by an accessor is borrowed and valid until
 *    the handle it came from is freed. Never pass a library allocation to free().
 *  - Functions that can fail return a datahub_status. Anything other than DATAHUB_OK and
 *    DATAHUB_BUFFERED leaves a message in datahub_last_error() (per thread; overwritten by the
 *    next failure on that thread) and, for HTTP failures, the status in datahub_last_http_status().
 *  - A datahub_client may be used from any number of threads at once. A datahub_listener and a
 *    datahub_message belong to one thread at a time.
 *  - Nothing here may be called from inside a Tokio runtime thread.
 */

#ifndef INTELLISTREAM_DATAHUB_H
#define INTELLISTREAM_DATAHUB_H

/* Generated by cbindgen from datahub_c_bindings/src. Edit the Rust sources; `cargo build` regenerates this file. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/* The library version this header was generated from. datahub_version() reports the
 * version actually loaded; the two should agree. */
#define DATAHUB_VERSION "0.3.0"
#define DATAHUB_VERSION_MAJOR 0
#define DATAHUB_VERSION_MINOR 3
#define DATAHUB_VERSION_PATCH 0

/* Pass as start_ms / end_ms to leave that end of a datapoint window open. */
#define DATAHUB_TIME_UNSET INT64_MIN


/**
 * Outcome of a call. Everything except `DATAHUB_OK` and `DATAHUB_BUFFERED` leaves a message
 * in `datahub_last_error()`.
 */
typedef enum {
  /**
   * The call succeeded. For an ingest call this means the data reached the server.
   */
  DATAHUB_OK = 0,
  /**
   * The data went into the on-disk spool because the server could not be reached, or refused
   * the credential. It is sent on a later ingest call or by `datahub_client_flush`. Not an
   * error: this is the answer an edge device wants when the network is down.
   */
  DATAHUB_BUFFERED = 1,
  /**
   * `datahub_listener_next`: nothing arrived within the timeout.
   */
  DATAHUB_TIMEOUT = 2,
  /**
   * `datahub_listener_next`: the stream has ended.
   */
  DATAHUB_CLOSED = 3,
  /**
   * The api answered with no item where exactly one was asked for.
   */
  DATAHUB_NOT_FOUND = 4,
  /**
   * A NULL where a value was required, invalid UTF-8, an empty id, a non-finite value, or a
   * JSON body that does not parse as the request the endpoint takes.
   */
  DATAHUB_INVALID_ARGUMENT = 10,
  /**
   * The configuration is incomplete or contradictory: no BASE_URL, no usable credential set,
   * a malformed URL.
   */
  DATAHUB_CONFIG = 11,
  /**
   * A token could not be obtained, or the api answered 401 or 403. For a 401 the message
   * includes the SDK's diagnosis of the token's `organization` claim when it has one.
   */
  DATAHUB_AUTH = 12,
  /**
   * The api answered another non-2xx status, or the request got no response at all;
   * `datahub_last_http_status()` says which. A transport failure (connection refused, DNS,
   * timeout) is reported as 503, the same way the core treats it: retryable.
   */
  DATAHUB_HTTP = 13,
  /**
   * A local failure: an env file that cannot be read, a runtime that could not start, a
   * WebSocket that could not be opened or was lost for good.
   */
  DATAHUB_IO = 14,
  /**
   * The listener reported an error for one subscription (unknown id, no read access). The
   * connection stays open and the other subscriptions keep delivering; call
   * `datahub_listener_next` again.
   */
  DATAHUB_SUBSCRIPTION = 15,
  /**
   * A Rust panic was caught at the boundary. The message is in `datahub_last_error()`;
   * please report it, it is a bug in the SDK.
   */
  DATAHUB_PANIC = 99,
} datahub_status;

/**
 * A connection to one DataHub api. Opaque; may be shared between threads; free with
 * `datahub_client_free` after every listener opened from it has been closed.
 */
typedef struct datahub_client datahub_client;

/**
 * Configuration for a `datahub_client`. Opaque; free with `datahub_config_free`.
 */
typedef struct datahub_config datahub_config;

/**
 * A live WebSocket listener over one or more subscriptions. Opaque; one thread at a time; close
 * (and free) with `datahub_listener_close`.
 */
typedef struct datahub_listener datahub_listener;

/**
 * One message delivered to a listener. Opaque; free with `datahub_message_free` after acking.
 */
typedef struct datahub_message datahub_message;

/**
 * One time series definition. Opaque; read it through the `datahub_timeseries_*` accessors and
 * free it with `datahub_timeseries_free`.
 */
typedef struct datahub_timeseries datahub_timeseries;

/**
 * One numeric datapoint to ingest.
 */
typedef struct {
  /**
   * Unix epoch milliseconds, UTC.
   */
  int64_t timestamp_ms;
  /**
   * Must be finite.
   */
  double value;
} datahub_datapoint;

/**
 * One datapoint as read back. Aggregates the api did not send are NaN, so a plain read never
 * needs a presence flag: a raw read carries `value`, an aggregated read the others.
 */
typedef struct {
  /**
   * Unix epoch milliseconds, UTC.
   */
  int64_t timestamp_ms;
  double value;
  double min;
  double max;
  double average;
  double sum;
} datahub_datapoint_agg;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library version, e.g. `"0.3.0"`. Static; never NULL. Compare with `DATAHUB_VERSION`.
 */
const char *datahub_version(void);

/**
 * Turn the SDK's console tracing (response bodies, batch progress, failed-request notices on
 * stdout/stderr) on or off for the whole process. Off by default in this library.
 */
void datahub_set_debug_output(bool enabled);

/**
 * Build a client from a config. The config is copied and may be freed afterwards. On success
 * `*out` is the client; on failure it is NULL and the status says why (`DATAHUB_CONFIG` for an
 * incomplete config, `DATAHUB_IO` if the runtime could not start). No request is made here:
 * tokens are fetched lazily on the first call that needs one.
 */
datahub_status datahub_client_new(const datahub_config *config, datahub_client **out);

/**
 * Release a client. Spooled data stays on disk for the next client that opens the same buffer
 * directory; call `datahub_client_flush` first if it should go out now. NULL is ignored.
 */
void datahub_client_free(datahub_client *client);

/**
 * Send whatever the datapoint and event spools hold, oldest first, without ingesting anything
 * new. `DATAHUB_OK` when both spools are empty afterwards; `DATAHUB_BUFFERED` when the server is
 * still unreachable and a backlog remains on disk. Always `DATAHUB_OK` when buffering is off.
 */
datahub_status datahub_client_flush(const datahub_client *client);

/**
 * Records (datapoints plus events) currently held in this client's on-disk spools. 0 when
 * buffering is off, or when nothing has been spooled by this client yet.
 */
uint64_t datahub_client_buffered_count(const datahub_client *client);

/**
 * An authenticated raw request to any api endpoint — the escape hatch for everything this
 * header has no dedicated function for. `method` is `GET` or `POST`; `path` is relative to the
 * base URL (`/events/count`, `/resources/filter`), a query string included; `body` is the JSON
 * request body (NULL sends `{}` for POST, nothing for GET). `*out` receives the raw response
 * body (empty for 204). No buffering applies here; the typed ingest functions have it.
 */
datahub_status datahub_request_json(const datahub_client *client,
                                    const char *method,
                                    const char *path,
                                    const char *body,
                                    char **out);

/**
 * A new, empty config. Never NULL.
 */
datahub_config *datahub_config_new(void);

/**
 * A config holding a snapshot of the process environment (every variable, so the usual
 * `BASE_URL`, `TOKEN`, `CLIENT_ID`, `BUFFER_DIR`, … are picked up). Never NULL. Does **not** read
 * a `.env` file; see `datahub_config_load_envfile`.
 */
datahub_config *datahub_config_from_env(void);

/**
 * Read a dotenv-style file (`KEY=value` lines) into the config, overriding any keys already
 * set. The process environment is left untouched. `DATAHUB_IO` when the file cannot be read,
 * `DATAHUB_INVALID_ARGUMENT` when a line does not parse.
 */
datahub_status datahub_config_load_envfile(datahub_config *config, const char *path);

/**
 * Set any configuration key by its environment name (`SCOPE`, `AUDIENCE`, `ASSERTION_GRANT`, …).
 * The typed setters below are conveniences over this. A NULL value removes the key.
 */
datahub_status datahub_config_set(datahub_config *config, const char *key, const char *value);

/**
 * Read a key back, or NULL when it is unset. Borrowed; valid until the same key is read again
 * on this thread. Meant for diagnostics, not for hot paths.
 */
const char *datahub_config_get(const datahub_config *config, const char *key);

/**
 * The api's root URL, e.g. `https://datahub.example.com`. Required.
 */
datahub_status datahub_config_set_base_url(datahub_config *config, const char *value);

/**
 * A bearer token used as-is and never refreshed; the alternative to client credentials.
 */
datahub_status datahub_config_set_token(datahub_config *config, const char *value);

/**
 * OAuth2 scope added to the token request. Against a realm using Keycloak Organizations this
 * must name the tenant: `organization:*`, or `organization:<alias>` to pin one.
 */
datahub_status datahub_config_set_scope(datahub_config *config, const char *value);

/**
 * OAuth2 audience for the token request. Required by Auth0, unused by Keycloak.
 */
datahub_status datahub_config_set_audience(datahub_config *config, const char *value);

/**
 * Optional project name.
 */
datahub_status datahub_config_set_project_name(datahub_config *config, const char *value);

/**
 * A ready-made JWT to exchange with the RFC 7523 `jwt-bearer` grant. Never refreshed; prefer
 * `datahub_config_set_assertion_credentials`.
 */
datahub_status datahub_config_set_assertion(datahub_config *config, const char *value);

/**
 * Scope for the assertion request; Entra ID needs `api://<app-id-uri>/.default`.
 */
datahub_status datahub_config_set_assertion_scope(datahub_config *config, const char *value);

/**
 * Audience for the assertion request.
 */
datahub_status datahub_config_set_assertion_audience(datahub_config *config, const char *value);

/**
 * Grant used in the secretless assertion mode: `client_credentials` (default) or `jwt-bearer`.
 */
datahub_status datahub_config_set_assertion_grant(datahub_config *config, const char *value);

/**
 * OAuth2 client credentials: the token endpoint mints and refreshes tokens with these. All three
 * are required for the flow to be configured at all.
 */
datahub_status datahub_config_set_client_credentials(datahub_config *config,
                                                     const char *client_id,
                                                     const char *client_secret,
                                                     const char *token_uri);

/**
 * Fetch the `jwt-bearer` assertion with client credentials from another provider (an Entra ID
 * app registration, say) and exchange it at the token URI. All three are required.
 */
datahub_status datahub_config_set_assertion_credentials(datahub_config *config,
                                                        const char *client_id,
                                                        const char *client_secret,
                                                        const char *token_uri);

/**
 * Turn on durable ingest buffering with the default bounds (72 h window, 5 GiB cap, directory
 * `.datahub-spool` under the working directory unless `datahub_config_set_buffer_dir` says
 * otherwise). Off by default.
 */
datahub_status datahub_config_enable_buffering(datahub_config *config);

/**
 * Directory for the on-disk spools. Also enables buffering: a host that names a spool directory
 * wants the spool.
 */
datahub_status datahub_config_set_buffer_dir(datahub_config *config, const char *dir);

/**
 * How long spooled records are kept, in seconds, measured on each record's own timestamp
 * (default 72 h). Also enables buffering.
 */
datahub_status datahub_config_set_buffer_retention_secs(datahub_config *config, int64_t seconds);

/**
 * Size cap for each spool in bytes; the oldest segment is dropped past it (default 5 GiB).
 * Also enables buffering.
 */
datahub_status datahub_config_set_buffer_max_bytes(datahub_config *config, uint64_t bytes);

/**
 * Release a config. The client it was used to build keeps its own copy. NULL is ignored.
 */
void datahub_config_free(datahub_config *config);

/**
 * Ingest `count` numeric datapoints into the series with this external id.
 *
 * `DATAHUB_OK` means they reached the server. With buffering enabled, `DATAHUB_BUFFERED` means
 * the server could not be reached (or refused the credential) and they are on disk, to be sent
 * on a later call: the on-disk backlog always goes first, so ordering holds. Retries are safe —
 * the server dedups on (series, timestamp). A non-finite value is `DATAHUB_INVALID_ARGUMENT`
 * before anything is sent. `count` of 0 is a no-op.
 *
 * The spool's retention window is measured on each datapoint's own timestamp, not on when it
 * was spooled: a backfill older than the window (72 h by default) is reported `DATAHUB_BUFFERED`
 * but does not survive in the spool. Backfill old data with buffering off, or widen the window.
 */
datahub_status datahub_datapoints_insert(const datahub_client *client,
                                         const char *external_id,
                                         const datahub_datapoint *points,
                                         size_t count);

/**
 * Ingest `count` string-valued datapoints (for text-typed series). `timestamps_ms[i]` pairs
 * with `values[i]`. Same status contract as `datahub_datapoints_insert`.
 */
datahub_status datahub_datapoints_insert_str(const datahub_client *client,
                                             const char *external_id,
                                             const int64_t *timestamps_ms,
                                             const char *const *values,
                                             size_t count);

/**
 * The most recent datapoint of a series, written into `*out`. `DATAHUB_NOT_FOUND` when the
 * series has no datapoints (or does not exist).
 */
datahub_status datahub_datapoints_latest(const datahub_client *client,
                                         const char *external_id,
                                         datahub_datapoint_agg *out);

/**
 * Raw datapoints of a series inside a window. `start_ms` is inclusive, `end_ms` exclusive;
 * pass `DATAHUB_TIME_UNSET` to leave either end open. `limit` of 0 means the server default.
 * `*out` receives an array of `*out_count` points, newest last, released with
 * `datahub_datapoints_free`; both are 0/NULL when the window is empty. For aggregated reads
 * (`aggregates`, `granularity`, paging with `cursor`) use `datahub_datapoints_retrieve_json`.
 */
datahub_status datahub_datapoints_retrieve(const datahub_client *client,
                                           const char *external_id,
                                           int64_t start_ms,
                                           int64_t end_ms,
                                           uint64_t limit,
                                           datahub_datapoint_agg **out,
                                           size_t *out_count);

/**
 * Release an array from `datahub_datapoints_retrieve`, with the count it came with. NULL is ignored.
 */
void datahub_datapoints_free(datahub_datapoint_agg *points,
                             size_t count);

/**
 * `POST /timeseries/data/list` with the full request: `body` is
 * `{"items":[{"externalId":…,"start":…,"end":…,"limit":…,"aggregates":[…],"granularity":…,"cursor":…}]}`
 * and `*out` receives the response envelope as the api sent it.
 */
datahub_status datahub_datapoints_retrieve_json(const datahub_client *client,
                                                const char *body,
                                                char **out);

/**
 * The message left by the last failing call on this thread, or `""` when there has been none.
 * Borrowed: valid until the next failing call on the same thread.
 */
const char *datahub_last_error(void);

/**
 * The HTTP status of the last `DATAHUB_HTTP` / `DATAHUB_AUTH` / `DATAHUB_NOT_FOUND` failure on
 * this thread, or 0 when the last failure was not an HTTP response.
 */
int datahub_last_http_status(void);

/**
 * The name of a status, e.g. `"DATAHUB_BUFFERED"`, for logging. Static; never NULL.
 */
const char *datahub_status_name(datahub_status status);

/**
 * `POST /events/create`. `body` is `{"items":[{"externalId":…,"type":…,"eventTime":…}, …]}`.
 * `DATAHUB_OK` with the created events in `*out`; with buffering enabled, `DATAHUB_BUFFERED`
 * (and `{"items":[]}`) when they went to the spool instead. Each event is stamped with a
 * time-ordered UUID before the first attempt, so a retry from the spool is not a duplicate.
 */
datahub_status datahub_events_create_json(const datahub_client *client,
                                          const char *body,
                                          char **out);

/**
 * `POST /events/filter`. `body` is `{"filter":{…},"limit":…,"cursor":…}`; page with the
 * response's `nextCursor`.
 */
datahub_status datahub_events_filter_json(const datahub_client *client,
                                          const char *body,
                                          char **out);

/**
 * Open a listener on `count` subscription external ids (0 is allowed; add them later with
 * `datahub_listener_subscribe`). The handshake fetches a token through the client. On a dropped
 * connection the listener reconnects on its own with backoff and resumes the same
 * subscriptions; anything not acked is redelivered.
 */
datahub_status datahub_listener_open(const datahub_client *client,
                                     const char *const *subscription_external_ids,
                                     size_t count,
                                     datahub_listener **out);

/**
 * Wait up to `timeout_ms` for the next message (negative waits indefinitely, 0 only takes what
 * has already arrived). `DATAHUB_OK` with the message in `*out`; `DATAHUB_TIMEOUT` with `*out`
 * NULL when nothing came; `DATAHUB_SUBSCRIPTION` when the server rejected one subscription (the
 * others keep delivering, call again); `DATAHUB_IO` when the connection was lost and could not
 * be re-established after several attempts (calling again retries). Call this often enough for
 * the server's 15 s pings to be answered, or the session is closed as idle and reconnected.
 */
datahub_status datahub_listener_next(datahub_listener *listener,
                                     int64_t timeout_ms,
                                     datahub_message **out);

/**
 * Acknowledge `count` message ids so they are not redelivered.
 */
datahub_status datahub_listener_ack(datahub_listener *listener,
                                    const char *const *message_ids,
                                    size_t count);

/**
 * Negative-acknowledge `count` message ids so they are redelivered.
 */
datahub_status datahub_listener_nack(datahub_listener *listener,
                                     const char *const *message_ids,
                                     size_t count);

/**
 * Add `count` subscriptions to the live set without reconnecting.
 */
datahub_status datahub_listener_subscribe(datahub_listener *listener,
                                          const char *const *subscription_external_ids,
                                          size_t count);

/**
 * Remove `count` subscriptions from the live set.
 */
datahub_status datahub_listener_unsubscribe(datahub_listener *listener,
                                            const char *const *subscription_external_ids,
                                            size_t count);

/**
 * Send a close frame, wait for the server's, and free the listener. Unacked messages are
 * redelivered to the next listener on the same subscriptions. NULL is ignored.
 */
datahub_status datahub_listener_close(datahub_listener *listener);

/**
 * The id to pass to `datahub_listener_ack`/`_nack`. Borrowed; valid until the message is freed.
 */
const char *datahub_message_id(const datahub_message *message);

/**
 * The subscription this message was delivered for. Borrowed.
 */
const char *datahub_message_subscription(const datahub_message *message);

/**
 * What happened: `CREATE`, `UPDATE`, `DELETE` or `RENAME`. Borrowed.
 */
const char *datahub_message_action(const datahub_message *message);

/**
 * What it happened to: `DATAPOINTS`, `TIMESERIES`, `EVENT`, `RESOURCE`, …. Borrowed.
 */
const char *datahub_message_object(const datahub_message *message);

/**
 * The whole message as JSON (`subscriptionExternalId`, `messageId`, `payload`). Borrowed.
 */
const char *datahub_message_json(const datahub_message *message);

/**
 * How many series this message carries datapoints for (0 unless the object is `DATAPOINTS`).
 */
size_t datahub_message_series_count(const datahub_message *message);

/**
 * External id of the `index`-th series, or NULL when the message named it by id only. Borrowed.
 */
const char *datahub_message_series_external_id(const datahub_message *message, size_t index);

/**
 * Numeric id of the `index`-th series, or 0 when the message did not carry one.
 */
uint64_t datahub_message_series_id(const datahub_message *message, size_t index);

/**
 * The datapoints of the `index`-th series as a borrowed array (valid until the message is
 * freed). A value that is not numeric reads as NaN, a timestamp that could not be parsed as
 * `INT64_MIN`; the JSON has the originals.
 */
datahub_status datahub_message_series_datapoints(const datahub_message *message,
                                                 size_t index,
                                                 const datahub_datapoint **out,
                                                 size_t *out_count);

/**
 * Release a message. NULL is ignored.
 */
void datahub_message_free(datahub_message *message);

/**
 * Look one time series up by external id. `DATAHUB_NOT_FOUND` when the api knows no such series
 * (or the caller may not read it — the api does not distinguish).
 */
datahub_status datahub_timeseries_get_by_external_id(const datahub_client *client,
                                                     const char *external_id,
                                                     datahub_timeseries **out);

/**
 * Release a time series handle. NULL is ignored.
 */
void datahub_timeseries_free(datahub_timeseries *ts);

/**
 * Numeric id; 0 when the api did not send one.
 */
uint64_t datahub_timeseries_id(const datahub_timeseries *ts);

/**
 * Numeric id of the data set the series belongs to; 0 when it has none.
 */
uint64_t datahub_timeseries_data_set_id(const datahub_timeseries *ts);

/**
 * External id. Borrowed; valid until the handle is freed.
 */
const char *datahub_timeseries_external_id(const datahub_timeseries *ts);

/**
 * Display name. Borrowed.
 */
const char *datahub_timeseries_name(const datahub_timeseries *ts);

/**
 * Unit symbol, or NULL when the series has none. Borrowed.
 */
const char *datahub_timeseries_unit(const datahub_timeseries *ts);

/**
 * Unit catalogue id, or NULL. Borrowed.
 */
const char *datahub_timeseries_unit_external_id(const datahub_timeseries *ts);

/**
 * Value type (`float`, `bigint`, `text`, …), or NULL when the endpoint did not say. Borrowed.
 */
const char *datahub_timeseries_value_type(const datahub_timeseries *ts);

/**
 * The whole definition as the api sent it, as JSON. Borrowed.
 */
const char *datahub_timeseries_json(const datahub_timeseries *ts);

/**
 * `POST /timeseries/create`. `body` is `{"items":[{"externalId":…,"name":…,"unit":…}, …]}`;
 * `*out` receives the created definitions in the same envelope.
 */
datahub_status datahub_timeseries_create_json(const datahub_client *client,
                                              const char *body,
                                              char **out);

/**
 * `POST /timeseries/search`: free-text search with optional narrowing. `body` is
 * `{"search":{"query":…},"filter":{…},"limit":…}`.
 */
datahub_status datahub_timeseries_search_json(const datahub_client *client,
                                              const char *body,
                                              char **out);

/**
 * `POST /timeseries/filter`: structured, AND-combined filtering. `body` is
 * `{"filter":{…},"limit":…,"cursor":…}`; page with the response's `nextCursor`.
 */
datahub_status datahub_timeseries_filter_json(const datahub_client *client,
                                              const char *body,
                                              char **out);

/**
 * Release a string the library handed out through a `char **` out-parameter. NULL is ignored.
 */
void datahub_string_free(char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* INTELLISTREAM_DATAHUB_H */
