"""Type stubs for the datahub_sdk pyo3 extension module.

The runtime is a single flat module: every class is exported at the top level.
This stub matches that structure; do not introduce submodules unless the Rust
registration in src/lib.rs::datahub_sdk() also adds them.
"""

from __future__ import annotations

import datetime
from typing import Any, Iterable, Iterator, Mapping, Optional, Sequence, Union
from uuid import UUID


# Convenience alias: every entity-like input accepts either the entity itself,
# an IdCollection wrapper, a numeric id, or an external_id string.
Identifiable = Union["TimeSeries", "Resource", "Unit", "Event", "IdCollection", int, str]


# ====================== Errors ======================

class DataHubException(Exception):
    """Raised when the DataHub API returns an error. `status_code` is the HTTP
    status (e.g. 400, 409) and `message` is the raw response body, so callers can
    branch on the code:

        try:
            client.resources.create(nodes, relations)
        except DataHubException as e:
            if e.status_code == 409:
                ...  # already exists
            elif e.status_code == 400:
                print(e.message)
    """
    status_code: int
    message: str


# ====================== Clients ======================

class DataHubClient:
    def __init__(
        self,
        base_url: str,
        token: str | None = None,
        token_url: str | None = None,
        client_id: str | None = None,
        client_secret: str | None = None,
        project_name: str | None = None,
    ) -> None: ...
    @classmethod
    def from_env(cls) -> DataHubClient: ...
    @classmethod
    def from_envfile(cls, path: str | None = None) -> DataHubClient: ...
    @property
    def timeseries(self) -> TimeSeriesServiceSync: ...
    @property
    def units(self) -> UnitServiceSync: ...
    @property
    def events(self) -> EventsServiceSync: ...
    @property
    def files(self) -> FileService: ...
    @property
    def resources(self) -> ResourcesServiceSync: ...
    @property
    def datasets(self) -> DatasetsServiceSync: ...
    @property
    def subscriptions(self) -> SubscriptionsServiceSync: ...
    @property
    def functions(self) -> FunctionsServiceSync: ...


class AsyncDataHubClient:
    def __init__(
        self,
        base_url: str,
        token: str | None = None,
        token_url: str | None = None,
        client_id: str | None = None,
        client_secret: str | None = None,
        project_name: str | None = None,
    ) -> None: ...
    @classmethod
    def from_env(cls) -> AsyncDataHubClient: ...
    @classmethod
    def from_envfile(cls, path: str | None = None) -> AsyncDataHubClient: ...
    @property
    def timeseries(self) -> TimeSeriesServiceAsync: ...
    @property
    def units(self) -> UnitServiceAsync: ...
    @property
    def events(self) -> EventsServiceAsync: ...
    @property
    def files(self) -> FileService: ...
    @property
    def resources(self) -> ResourcesServiceAsync: ...
    @property
    def subscriptions(self) -> SubscriptionsServiceAsync: ...
    @property
    def functions(self) -> FunctionsServiceAsync: ...


# ====================== Identifiers & search ======================

class IdCollection:
    def __init__(self, id: int,external_id: str) -> None: ...
    @property
    def id(self) -> int | None: ...
    @property
    def external_id(self) -> str | None: ...


class SearchAndFilterForm: ...


# ====================== Field update wrappers ======================

class FieldStr:
    def __init__(self, value: str | None = None, set_null: bool = False) -> None: ...
    @property
    def value(self) -> str | None: ...
    @property
    def set_null(self) -> bool: ...


class FieldU64:
    def __init__(self, value: int | None = None, set_null: bool = False) -> None: ...
    @property
    def value(self) -> int | None: ...
    @property
    def set_null(self) -> bool: ...


class ListFieldU64:
    def __init__(
        self,
        remove: list[int] | None = None,
        add: list[int] | None = None,
        set: list[int] | None = None,
    ) -> None: ...
    @property
    def set(self) -> list[int] | None: ...
    @property
    def add(self) -> list[int] | None: ...
    @property
    def remove(self) -> list[int] | None: ...


class ListFieldStr:
    def __init__(
        self,
        remove: list[str] | None = None,
        add: list[str] | None = None,
        set: list[str] | None = None,
    ) -> None: ...
    @property
    def set(self) -> list[str] | None: ...
    @property
    def add(self) -> list[str] | None: ...
    @property
    def remove(self) -> list[str] | None: ...


class MapField:
    def __init__(
        self,
        remove: list[str] | None = None,
        add: dict[str, str] | None = None,
        set: dict[str, str] | None = None,
    ) -> None: ...
    @property
    def set(self) -> dict[str, str] | None: ...
    @property
    def add(self) -> dict[str, str] | None: ...
    @property
    def remove(self) -> list[str] | None: ...


# ====================== Time series ======================

class TimeSeries:
    def __init__(
        self,
        external_id: str,
        name: str | None = None,
        value_type: str | ValueType | None = None,
        unit: str | None = None,
        unit_external_id: str | None = None,
        description: str | None = None,
        metadata: dict[str, str] | None = None,
        security_categories: list[int] | None = None,
        data_set_id: int | None = None,
        id: int | None = None,
        relations_from: list[RelationFrom] | None = None,
    ) -> None: ...
    @property
    def id(self) -> int | None: ...
    @property
    def external_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def unit(self) -> str | None: ...
    @property
    def unit_external_id(self) -> str | None: ...
    @property
    def value_type(self) -> str | None: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    @property
    def security_categories(self) -> list[int] | None: ...
    @property
    def data_set_id(self) -> int | None: ...
    @property
    def relations_from(self) -> list[RelationFrom] | None: ...


class RelationFrom:
    def __init__(self, entity: Identifiable, relationship_type: str) -> None: ...


class TimeSeriesUpdate:
    def __init__(
        self,
        ts: Identifiable,
        external_id: FieldStr | None = None,
        name: FieldStr | None = None,
        metadata: MapField | None = None,
        unit: FieldStr | None = None,
        description: FieldStr | None = None,
        unit_external_id: FieldStr | None = None,
        security_categories: ListFieldU64 | None = None,
        data_set_id: FieldU64 | None = None,
        relations_from: ListFieldU64 | None = None,
        value_type: ValueType | None = None,
    ) -> None: ...
    @property
    def target_external_id(self) -> str | None: ...
    @property
    def target_id(self) -> int | None: ...
    @property
    def external_id(self) -> FieldStr: ...
    @property
    def name(self) -> FieldStr: ...
    @property
    def metadata(self) -> MapField: ...
    @property
    def unit(self) -> FieldStr: ...
    @property
    def description(self) -> FieldStr: ...
    @property
    def unit_external_id(self) -> FieldStr: ...
    @property
    def security_categories(self) -> ListFieldU64: ...
    @property
    def data_set_id(self) -> FieldU64: ...
    @property
    def relations_from(self) -> ListFieldU64: ...
    @property
    def value_type(self) -> str | None: ...


class DeleteFilter:
    def __init__(
        self,
        ts: Identifiable,
        inclusive_begin: datetime.datetime | None = None,
        exclusive_end: datetime.datetime | None = None,
    ) -> None: ...
    @property
    def target_id(self) -> int | None: ...
    @property
    def target_external_id(self) -> int | None: ...
    @property
    def inclusive_begin(self) -> datetime.datetime | None: ...
    @property
    def exclusive_end(self) -> datetime.datetime | None: ...


class ValueType:
    def __init__(self, value: str) -> None: ...
    def __repr__(self) -> str: ...


class Datapoint:
    def __init__(
        self,
        timestamp: datetime.datetime,
        value: float | None = None,
        min: float | None = None,
        max: float | None = None,
        average: float | None = None,
        sum: float | None = None,
    ) -> None: ...
    @property
    def timestamp(self) -> datetime.datetime: ...
    @property
    def value(self) -> float | None: ...
    @property
    def min(self) -> float | None: ...
    @property
    def max(self) -> float | None: ...
    @property
    def average(self) -> float | None: ...
    @property
    def sum(self) -> float | None: ...
    def __str__(self) -> str: ...


class DatapointString:
    def __init__(self, ts: datetime.datetime, value: str) -> None: ...
    @classmethod
    def from_int(cls, ts: datetime.datetime, value: int) -> DatapointString: ...
    @classmethod
    def from_float(cls, ts: datetime.datetime, value: float) -> DatapointString: ...
    @property
    def timestamp(self) -> str: ...
    @timestamp.setter
    def timestamp(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...


class DatapointsCollectionString:
    def get_datapoints(self) -> list[Datapoint]: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    @property
    def next_cursor(self) -> str | None: ...
    @property
    def id(self) -> int | None: ...


class DatapointsCollectionDatapoints:
    def get_datapoints(self) -> list[Datapoint]: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    @property
    def next_cursor(self) -> str | None: ...
    @property
    def id(self) -> int | None: ...


class RetrieveFilter:
    def __init__(
        self,
        ts: Identifiable,
        start: datetime.datetime | None = None,
        end: datetime.datetime | None = None,
        limit: int | None = None,
        aggregates: list[str] | None = None,
        granularity: str | None = None,
        cursor: str | None = None,
    ) -> None: ...
    @property
    def start(self) -> datetime.datetime | None: ...
    @property
    def end(self) -> datetime.datetime | None: ...
    @property
    def limit(self) -> int | None: ...
    @property
    def aggregates(self) -> list[str] | None: ...
    @property
    def granularity(self) -> str | None: ...
    @property
    def cursor(self) -> str | None: ...


class TimeSeriesServiceSync:
    def list(self) -> list[TimeSeries]: ...
    def create(self, input: list[TimeSeries]) -> list[TimeSeries]: ...
    def by_ids(self, input: list[Identifiable]) -> list[TimeSeries]: ...
    def delete(self, input: list[Identifiable]) -> None: ...
    def update(self, input: list[TimeSeriesUpdate]) -> list[TimeSeries]: ...
    def search(self, input: SearchAndFilterForm) -> list[TimeSeries]: ...
    def insert_datapoints(self, input: list[DatapointsCollectionString]) -> list[str]: ...
    def insert_from_lists(
        self,
        timestamps: list[datetime.datetime],
        values: list[float],
        ts: Identifiable,
    ) -> list[str]: ...
    def retrieve_datapoints(self, input: RetrieveFilter) -> list[DatapointsCollectionDatapoints]: ...
    def delete_datapoints(self, input: list[DeleteFilter]) -> None: ...
    def retrieve_latest_datapoints(
        self, input: list[Identifiable]
    ) -> list[DatapointsCollectionDatapoints]: ...


class TimeSeriesServiceAsync:
    async def list(self) -> list[TimeSeries]: ...
    async def create(self, input: list[TimeSeries]) -> list[TimeSeries]: ...
    async def by_ids(self, input: list[Identifiable]) -> list[TimeSeries]: ...
    async def delete(self, input: list[Identifiable]) -> None: ...
    async def update(self, input: list[TimeSeriesUpdate]) -> list[TimeSeries]: ...
    async def search(self, input: SearchAndFilterForm) -> list[TimeSeries]: ...
    async def insert_datapoints(self, input: list[DatapointsCollectionString]) -> list[str]: ...
    async def insert_from_lists(
        self,
        timestamps: list[datetime.datetime],
        values: list[float],
        ts: Identifiable,
    ) -> list[str]: ...
    async def retrieve_datapoints(
        self, input: RetrieveFilter
    ) -> list[DatapointsCollectionDatapoints]: ...
    async def delete_datapoints(self, input: list[DeleteFilter]) -> None: ...
    async def retrieve_latest_datapoints(
        self, input: list[Identifiable]
    ) -> list[DatapointsCollectionDatapoints]: ...


# ====================== Events ======================

class Event:
    def __init__(
        self,
        external_id: str,
        type: str | None = None,
        sub_type: str | None = None,
        description: str | None = None,
        status: str | None = None,
        source: str | None = None,
        metadata: dict[str, str] | None = None,
        data_set_id: int | None = None,
        related_resource_ids: list[int] | None = None,
        related_resource_external_ids: list[str] | None = None,
        event_time: datetime.datetime | None = None,
        id: UUID | None = None,
    ) -> None: ...
    @property
    def id(self) -> UUID | None: ...
    @property
    def external_id(self) -> str: ...


class TimeFilter:
    def __init__(
        self,
        start: datetime.datetime | None = None,
        end: datetime.datetime | None = None,
    ) -> None: ...


class BasicEventFilter:
    def __init__(
        self,
        id: int | None = None,
        external_id_prefix: str | None = None,
        description: str | None = None,
        source: str | None = None,
        type: str | None = None,
        sub_type: str | None = None,
        data_set_ids: list[int] | None = None,
        event_time: TimeFilter | None = None,
        metadata: dict[str, str] | None = None,
        related_resource_ids: list[int] | None = None,
        related_resource_external_ids: list[str] | None = None,
        created_time: TimeFilter | None = None,
        last_updated_time: TimeFilter | None = None,
    ) -> None: ...


class EventFilter:
    def __init__(self, basic_filter: BasicEventFilter, limit: int | None = None) -> None: ...
    @property
    def filter(self) -> BasicEventFilter | None: ...
    @property
    def limit(self) -> int: ...
    @limit.setter
    def limit(self, value: int) -> None: ...
    @property
    def cursor(self) -> str | None: ...


class EventIdCollection:
    @property
    def id(self) -> UUID | None: ...
    @property
    def external_id(self) -> str | None: ...


EventIdentifiable = Union[Event, EventIdCollection, UUID, str]


class EventsServiceSync:
    def create(self, input: list[Event]) -> list[Event]: ...
    def by_ids(self, input: list[EventIdentifiable]) -> list[Event]: ...
    def delete(self, input: list[EventIdentifiable]) -> None: ...
    def filter(self, input: EventFilter) -> list[Event]: ...


class EventsServiceAsync:
    async def create(self, input: list[Event]) -> list[Event]: ...
    async def by_ids(self, input: list[EventIdentifiable]) -> list[Event]: ...
    async def delete(self, input: list[EventIdentifiable]) -> None: ...
    async def filter(self, input: EventFilter) -> list[Event]: ...


# ====================== Datasets ======================

class Dataset:
    def __init__(
        self,
        external_id: str,
        name: str | None = None,
        id: int | None = None,
        description: str | None = None,
        policies: list[str] | None = None,
        metadata: dict[str, str] | None = None,
        connected_data_sets: list[int] | None = None,
    ) -> None: ...
    @property
    def external_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> int | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def policies(self) -> list[str] | None: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    @property
    def connected_data_sets(self) -> list[int]: ...


class DatasetsServiceSync:
    def create(self, input: list[Dataset]) -> list[Dataset]: ...
    def by_ids(self, input: list[Identifiable]) -> list[Dataset]: ...
    def delete(self, input: list[Identifiable]) -> None: ...


class DatasetsServiceAsync:
    async def list(self) -> list[Dataset]: ...
    async def create(self, input: list[Dataset]) -> list[Dataset]: ...
    async def by_ids(self, input: list[Identifiable]) -> list[Dataset]: ...
    async def delete(self, input: list[Identifiable]) -> None: ...


# ====================== Resources ======================

class Resource:
    def __init__(
        self,
        name: str | None = None,
        external_id: str | None = None,
        id: int | None = None,
        metadata: dict[str, str] | None = None,
        description: str | None = None,
        is_root: bool = False,
        data_set_id: int | None = None,
        source: str | None = None,
        labels: list[str] | None = None,
        relations: list[EdgeProxy] | None = None,
        geolocation: dict[str, float] | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def external_id(self) -> str: ...
    @property
    def id(self) -> int | None: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def data_set_id(self) -> int | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def labels(self) -> list[str] | None: ...
    @property
    def relations(self) -> list[EdgeProxy] | None: ...
    @property
    def geolocation(self) -> dict[str, float] | None: ...
    @property
    def created_time(self) -> datetime.datetime | None: ...
    @property
    def last_updated_time(self) -> datetime.datetime | None: ...


# ====================== Relations ======================
# NOTE: `RelForm` (graph/resources relation form) is distinct from the legacy
# `RelationFrom` used by timeseries — both intentionally coexist.

class EdgeProxy:
    """Server-assigned edge between two resources. The `relationship_type`
    attribute maps to the wire field `"type"`."""
    def __init__(
        self,
        id: int | None = None,
        start: int | None = None,
        end: int | None = None,
        relationship_type: str | None = None,
        description: str | None = None,
        relationship_type_id: int | None = None,
        metadata: dict[str, str] | None = None,
    ) -> None: ...
    @property
    def id(self) -> int | None: ...
    @property
    def start(self) -> int | None: ...
    @property
    def end(self) -> int | None: ...
    @property
    def relationship_type(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def relationship_type_id(self) -> int | None: ...
    @property
    def metadata(self) -> dict[str, str]: ...


class RelForm:
    """Request-side edge form. Pair with a list of `Resource` and pass both to
    `ResourcesService.create()`. `relationship_type` is keyword-required."""
    def __init__(
        self,
        *,
        relationship_type: str,
        from_external_id: str | None = None,
        to_external_id: str | None = None,
        from_id: int | None = None,
        to_id: int | None = None,
        id: int | None = None,
        relationship_type_id: int | None = None,
        metadata: dict[str, str] | None = None,
        data_set_id: int | None = None,
        description: str | None = None,
    ) -> None: ...
    @classmethod
    def by_external_ids(
        cls, from_external_id: str, to_external_id: str, relationship_type: str
    ) -> RelForm: ...
    @classmethod
    def by_ids(cls, from_id: int, to_id: int, relationship_type: str) -> RelForm: ...
    @property
    def id(self) -> int | None: ...
    @property
    def from_external_id(self) -> str | None: ...
    @property
    def to_external_id(self) -> str | None: ...
    @property
    def from_id(self) -> int | None: ...
    @property
    def to_id(self) -> int | None: ...
    @property
    def relationship_type(self) -> str: ...
    @property
    def relationship_type_id(self) -> int | None: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    @property
    def data_set_id(self) -> int | None: ...
    @property
    def description(self) -> str | None: ...


class GraphResult:
    """Nodes and relations returned from a graph operation."""
    @property
    def nodes(self) -> list[Resource]: ...
    @property
    def relations(self) -> list[EdgeProxy]: ...


ResourceIdentifiable = Union[Resource, str, int]


class ResourcesServiceSync:
    def create(
        self, nodes: list[Resource], relations: list[RelForm] | None = None
    ) -> GraphResult: ...
    def by_ids(self, input: list[ResourceIdentifiable]) -> list[Resource]: ...
    def delete(self, input: list[ResourceIdentifiable]) -> None: ...
    def search(self, input: SearchAndFilterForm) -> list[Resource]: ...


class ResourcesServiceAsync:
    async def create(
        self, nodes: list[Resource], relations: list[RelForm] | None = None
    ) -> GraphResult: ...
    async def by_ids(self, input: list[ResourceIdentifiable]) -> list[Resource]: ...
    async def delete(self, input: list[ResourceIdentifiable]) -> None: ...
    async def search(self, input: SearchAndFilterForm) -> list[Resource]: ...


# ====================== Units ======================

class Unit:
    def __init__(
        self,
        id: int,
        external_id: str,
        name: str,
        long_name: str,
        symbol: str,
        description: str,
        alias_names: list[str],
        quantity: str,
        conversion: dict[str, float],
        source: str,
        source_reference: str,
    ) -> None: ...


class UnitServiceSync:
    def list(self) -> list[Unit]: ...
    def by_ids(self, input: list[IdCollection]) -> list[Unit]: ...
    def by_external_ids(self, input: str) -> list[Unit]: ...


class UnitServiceAsync:
    async def list(self) -> list[Unit]: ...
    async def by_ids(self, input: list[IdCollection]) -> list[Unit]: ...
    async def by_external_id(self, input: str) -> list[Unit]: ...


# ====================== Files ======================

class FileService:
    async def list_root_directory(self) -> str: ...


class INode:
    def __init__(
        self,
        name: str,
        external_id: str,
        path: str,
        size: int,
        id: int | None = None,
        description: str | None = None,
        checksum: str | None = None,
        source: str | None = None,
        type: str | None = None,
        mime_type: str | None = None,
        source_date_created: datetime.datetime | None = None,
        source_last_updated: datetime.datetime | None = None,
        parent_id: int | None = None,
        parent_external_id: str | None = None,
        data_set_id: int | None = None,
        metadata: dict[str, str] | None = None,
        related_resources: list[int] | None = None,
        security_categories: list[int] | None = None,
    ) -> None: ...
    @property
    def id(self) -> int | None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def external_id(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def checksum(self) -> str | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def type(self) -> str | None: ...
    @property
    def mime_type(self) -> str | None: ...
    @property
    def source_date_created(self) -> datetime.datetime | None: ...
    @property
    def source_last_updated(self) -> datetime.datetime | None: ...
    @property
    def date_created(self) -> datetime.datetime: ...
    @property
    def last_updated(self) -> datetime.datetime: ...
    @property
    def parent_id(self) -> int | None: ...
    @property
    def parent_external_id(self) -> str | None: ...
    @property
    def data_set_id(self) -> int | None: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    @property
    def related_resources(self) -> list[int] | None: ...
    @property
    def security_categories(self) -> list[int] | None: ...


class FileUpload:
    def __init__(
        self,
        path: str,
        destination_path: str | None = None,
        external_id: str | None = None,
        name: str | None = None,
        metadata: dict[str, str] | None = None,
        description: str | None = None,
        source: str | None = None,
        data_set_id: int | None = None,
        related_resources: list[int] | None = None,
    ) -> None: ...
    @classmethod
    def from_path(cls, path: str) -> FileUpload: ...
    @classmethod
    def new_with_destination_path(cls, path: str, destination_path: str) -> FileUpload: ...
    @property
    def external_id(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def destination_path(self) -> str | None: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def data_set_id(self) -> int | None: ...
    @property
    def mime_type(self) -> str | None: ...
    @property
    def related_resources(self) -> list[int] | None: ...
    @property
    def source_date_created(self) -> datetime.datetime | None: ...
    @property
    def source_last_updated(self) -> datetime.datetime | None: ...


FileIdentifiable = Union[INode, IdCollection, int, str]


class FilesServiceSync:
    def upload_file(self, file_upload: FileUpload) -> FileUpload: ...
    def list_root_directory(self) -> list[INode]: ...
    def delete(self, input: list[FileIdentifiable]) -> None: ...
    def list_directory_by_path(self, path: str) -> list[INode]: ...


class FilesServiceAsync:
    async def upload_file(self, file_upload: FileUpload) -> list[FileUpload]: ...
    async def list_root_directory(self) -> list[INode]: ...
    async def delete(self, input: list[FileIdentifiable]) -> None: ...
    async def list_directory_by_path(self, path: str) -> list[INode]: ...


# ====================== Subscriptions ======================

class Subscription:
    def __init__(
        self,
        external_id: str,
        name: str,
        timeseries: list[Identifiable],
        id: int | None = None,
    ) -> None: ...


SubscriptionTimeseriesId = Union[TimeSeries, IdCollection, int, str]


class SubscriptionFilter:
    def __init__(self, timeseries: list[SubscriptionTimeseriesId] | None = None) -> None: ...
    @property
    def timeseries(self) -> list[IdCollection]: ...


class DataSort:
    def __init__(
        self,
        property: list[str] | None = None,
        order: str | None = None,
        nulls: str | None = None,
    ) -> None: ...
    @property
    def property(self) -> list[str] | None: ...
    @property
    def order(self) -> str | None: ...
    @property
    def nulls(self) -> str | None: ...


class SubscriptionRetriever:
    def __init__(
        self,
        filter: SubscriptionFilter | None = None,
        limit: int | None = None,
        sort: DataSort | None = None,
    ) -> None: ...
    @property
    def filter(self) -> SubscriptionFilter: ...
    @property
    def limit(self) -> int: ...
    @property
    def sort(self) -> DataSort: ...


class EventAction:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


class EventObject:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


class WsDatapoint:
    @property
    def timestamp(self) -> str: ...
    @property
    def value(self) -> str: ...
    def as_float(self) -> float: ...


class DataCollectionString:
    @property
    def id(self) -> int | None: ...
    @property
    def external_id(self) -> str | None: ...
    @property
    def value_type(self) -> str | None: ...
    @property
    def inclusive_begin(self) -> str | None: ...
    @property
    def exclusive_end(self) -> str | None: ...
    @property
    def datapoints(self) -> list[WsDatapoint]: ...


class DataWrapperMessage:
    @property
    def event_action(self) -> EventAction: ...
    @property
    def event_object(self) -> EventObject: ...
    @property
    def tenant_id(self) -> str | None: ...
    @property
    def items(self) -> list[DataCollectionString]: ...


class SubscriptionMessage:
    @property
    def message_id(self) -> str: ...
    @property
    def payload(self) -> DataWrapperMessage: ...


SubscriptionIdentifiable = Union[Subscription, IdCollection, int, str]


class SubscriptionListener:
    def __iter__(self) -> SubscriptionListener: ...
    def __next__(self) -> SubscriptionMessage: ...
    def next_message(self) -> SubscriptionMessage | None: ...
    def ack(self, message_ids: list[str]) -> None: ...
    def nack(self, message_ids: list[str]) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> SubscriptionListener: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...


class SubscriptionListenerAsync:
    def __aiter__(self) -> SubscriptionListenerAsync: ...
    async def __anext__(self) -> SubscriptionMessage: ...
    async def next_message(self) -> SubscriptionMessage | None: ...
    async def ack(self, message_ids: list[str]) -> None: ...
    async def nack(self, message_ids: list[str]) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> SubscriptionListenerAsync: ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...


class SubscriptionsServiceSync:
    def create(self, input: list[Subscription]) -> list[Subscription]: ...
    def list(
        self,
        retriever: SubscriptionRetriever | None = None,
        timeseries: list[SubscriptionTimeseriesId] | None = None,
        limit: int | None = None,
        sort: DataSort | None = None,
    ) -> list[Subscription]: ...
    def delete(self, input: list[SubscriptionIdentifiable]) -> None: ...
    def listen(self, subscription_external_id: str) -> SubscriptionListener: ...


class SubscriptionsServiceAsync:
    async def create(self, input: list[Subscription]) -> list[Subscription]: ...
    async def list(
        self,
        retriever: SubscriptionRetriever | None = None,
        timeseries: list[SubscriptionTimeseriesId] | None = None,
        limit: int | None = None,
        sort: DataSort | None = None,
    ) -> list[Subscription]: ...
    async def delete(self, input: list[SubscriptionIdentifiable]) -> None: ...
    async def listen(self, subscription_external_id: str) -> SubscriptionListenerAsync: ...


# ====================== Functions ======================

class Function:
    def __init__(
        self,
        external_id: str,
        model_name: str,
        name: str | None = None,
        config: dict[str, Any] | None = None,
    ) -> None: ...
    @property
    def id(self) -> int | None: ...
    @property
    def external_id(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def model_name(self) -> str: ...
    @property
    def config(self) -> Any: ...
    @property
    def labels(self) -> list[str]: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    @property
    def created_time(self) -> datetime.datetime | None: ...
    @property
    def last_updated_time(self) -> datetime.datetime | None: ...
    @property
    def relations(self) -> list[EdgeProxy]: ...


FunctionIdentifiable = Union[Function, IdCollection, int, str]


class FunctionsServiceSync:
    def create(self, input: list[Function]) -> list[Function]: ...
    def list(self) -> list[Function]: ...
    def by_ids(self, input: list[FunctionIdentifiable]) -> list[Function]: ...
    def by_external_id(self, external_id: str) -> Function: ...
    def delete(self, input: list[FunctionIdentifiable]) -> None: ...


class FunctionsServiceAsync:
    async def create(self, input: list[Function]) -> list[Function]: ...
    async def list(self) -> list[Function]: ...
    async def by_ids(self, input: list[FunctionIdentifiable]) -> list[Function]: ...
    async def by_external_id(self, external_id: str) -> Function: ...
    async def delete(self, input: list[FunctionIdentifiable]) -> None: ...
