// SPDX-License-Identifier: Apache-2.0
//! `datahub_config`: the values a client is built from.
//!
//! A config is a map keyed by the same names the environment uses (`BASE_URL`, `TOKEN`,
//! `CLIENT_ID`, …, `BUFFER_DIR`), so the environment, an env file and the typed setters all feed
//! one code path: `DataHubConfig::from_map` in the core. Nothing here reads or writes the process
//! environment unless `datahub_config_from_env` is called, and nothing ever reads a `.env` file
//! from the working directory — a library must not pick up a dotfile from the host's cwd.
//!
//! Every export is written out by hand rather than generated by a macro: cbindgen does not expand
//! `macro_rules!`, so a macro-generated function would exist in the library but not in the header.

use std::collections::HashMap;
use std::env;
use std::ffi::c_char;
use std::path::Path;

use intellistream_datahub_sdk::datahub::DataHubConfig;
use intellistream_datahub_sdk::errors::DataHubError;

use crate::error::{datahub_status, fail, guard};
use crate::util::{mut_arg, opt_str_arg, ref_arg, str_arg};

/// Configuration for a `datahub_client`. Opaque; free with `datahub_config_free`.
pub struct datahub_config {
    pub(crate) values: HashMap<String, String>,
}

impl datahub_config {
    pub(crate) fn build(&self) -> Result<DataHubConfig, DataHubError> {
        DataHubConfig::from_map(self.values.clone())
    }

    pub(crate) fn get(&self, key: &str) -> Option<&str> {
        self.values.get(key).map(String::as_str)
    }

    fn set(&mut self, key: &str, value: &str) {
        self.values.insert(key.to_string(), value.to_string());
    }
}

/// A new, empty config. Never NULL.
#[no_mangle]
pub extern "C" fn datahub_config_new() -> *mut datahub_config {
    Box::into_raw(Box::new(datahub_config {
        values: HashMap::new(),
    }))
}

/// A config holding a snapshot of the process environment (every variable, so the usual
/// `BASE_URL`, `TOKEN`, `CLIENT_ID`, `BUFFER_DIR`, … are picked up). Never NULL. Does **not** read
/// a `.env` file; see `datahub_config_load_envfile`.
#[no_mangle]
pub extern "C" fn datahub_config_from_env() -> *mut datahub_config {
    Box::into_raw(Box::new(datahub_config {
        values: env::vars().collect(),
    }))
}

/// Parse dotenv-style text: one `KEY=value` per line, `#` comments, blank lines, an optional
/// `export ` prefix, and single or double quotes around a value. Nothing fancier — the same
/// subset every `.env` in this project uses.
pub(crate) fn parse_env_text(text: &str) -> Result<Vec<(String, String)>, String> {
    let mut entries = Vec::new();
    for (index, raw) in text.lines().enumerate() {
        let number = index + 1;
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").unwrap_or(line).trim_start();
        let Some((key, value)) = line.split_once('=') else {
            return Err(format!("line {number}: expected KEY=value"));
        };
        let key = key.trim();
        if key.is_empty() || !key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            return Err(format!("line {number}: {key:?} is not a valid key"));
        }
        let value = value.trim();
        let value = match value.chars().next() {
            Some(quote @ ('"' | '\'')) => match value[1..].find(quote) {
                Some(end) => &value[1..1 + end],
                None => return Err(format!("line {number}: unterminated quote")),
            },
            _ => value.split(" #").next().unwrap_or(value).trim(),
        };
        entries.push((key.to_string(), value.to_string()));
    }
    Ok(entries)
}

/// Read a dotenv-style file (`KEY=value` lines) into the config, overriding any keys already
/// set. The process environment is left untouched. `DATAHUB_IO` when the file cannot be read,
/// `DATAHUB_INVALID_ARGUMENT` when a line does not parse.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_load_envfile(
    config: *mut datahub_config,
    path: *const c_char,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        let path = ffi_try!(str_arg(path, "path"));
        let text = match std::fs::read_to_string(Path::new(path)) {
            Ok(text) => text,
            Err(e) => {
                return fail(
                    datahub_status::DATAHUB_IO,
                    0,
                    format!("cannot read env file {path}: {e}"),
                )
            }
        };
        match parse_env_text(&text) {
            Ok(entries) => {
                for (key, value) in entries {
                    config.set(&key, &value);
                }
                datahub_status::DATAHUB_OK
            }
            Err(e) => fail(
                datahub_status::DATAHUB_INVALID_ARGUMENT,
                0,
                format!("cannot parse env file {path}: {e}"),
            ),
        }
    })
}

/// Set any configuration key by its environment name (`SCOPE`, `AUDIENCE`, `ASSERTION_GRANT`, …).
/// The typed setters below are conveniences over this. A NULL value removes the key.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set(
    config: *mut datahub_config,
    key: *const c_char,
    value: *const c_char,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        let key = ffi_try!(str_arg(key, "key"));
        if key.trim().is_empty() {
            return fail(
                datahub_status::DATAHUB_INVALID_ARGUMENT,
                0,
                "key must not be empty",
            );
        }
        match ffi_try!(opt_str_arg(value, "value")) {
            Some(value) => config.set(key, value),
            None => {
                config.values.remove(key);
            }
        }
        datahub_status::DATAHUB_OK
    })
}

thread_local! {
    /// `datahub_config_get` hands out NUL-terminated copies; they live here so the pointer stays
    /// valid until the same key is read again on this thread, or the thread ends.
    static GET_CACHE: std::cell::RefCell<HashMap<String, std::ffi::CString>> =
        std::cell::RefCell::new(HashMap::new());
}

/// Read a key back, or NULL when it is unset. Borrowed; valid until the same key is read again
/// on this thread. Meant for diagnostics, not for hot paths.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_get(
    config: *const datahub_config,
    key: *const c_char,
) -> *const c_char {
    let (Some(config), false) = (config.as_ref(), key.is_null()) else {
        return std::ptr::null();
    };
    let Ok(key) = std::ffi::CStr::from_ptr(key).to_str() else {
        return std::ptr::null();
    };
    match config.values.get(key) {
        Some(value) => GET_CACHE.with(|cache| {
            let mut cache = cache.borrow_mut();
            cache.insert(key.to_string(), crate::util::to_cstring(value));
            cache[key].as_ptr()
        }),
        None => std::ptr::null(),
    }
}

/// The body every typed string setter shares.
unsafe fn set_key(config: *mut datahub_config, key: &str, value: *const c_char) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        let value = ffi_try!(str_arg(value, "value"));
        config.set(key, value);
        datahub_status::DATAHUB_OK
    })
}

/// The api's root URL, e.g. `https://datahub.example.com`. Required.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_base_url(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "BASE_URL", value)
}

/// A bearer token used as-is and never refreshed; the alternative to client credentials.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_token(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "TOKEN", value)
}

/// OAuth2 scope added to the token request. Against a realm using Keycloak Organizations this
/// must name the tenant: `organization:*`, or `organization:<alias>` to pin one.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_scope(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "SCOPE", value)
}

/// OAuth2 audience for the token request. Required by Auth0, unused by Keycloak.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_audience(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "AUDIENCE", value)
}

/// Optional project name.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_project_name(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "PROJECT_NAME", value)
}

/// A ready-made JWT to exchange with the RFC 7523 `jwt-bearer` grant. Never refreshed; prefer
/// `datahub_config_set_assertion_credentials`.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_assertion(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "ASSERTION", value)
}

/// Scope for the assertion request; Entra ID needs `api://<app-id-uri>/.default`.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_assertion_scope(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "ASSERTION_SCOPE", value)
}

/// Audience for the assertion request.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_assertion_audience(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "ASSERTION_AUDIENCE", value)
}

/// Grant used in the secretless assertion mode: `client_credentials` (default) or `jwt-bearer`.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_assertion_grant(
    config: *mut datahub_config,
    value: *const c_char,
) -> datahub_status {
    set_key(config, "ASSERTION_GRANT", value)
}

/// OAuth2 client credentials: the token endpoint mints and refreshes tokens with these. All three
/// are required for the flow to be configured at all.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_client_credentials(
    config: *mut datahub_config,
    client_id: *const c_char,
    client_secret: *const c_char,
    token_uri: *const c_char,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        let client_id = ffi_try!(str_arg(client_id, "client_id"));
        let client_secret = ffi_try!(str_arg(client_secret, "client_secret"));
        let token_uri = ffi_try!(str_arg(token_uri, "token_uri"));
        config.set("CLIENT_ID", client_id);
        config.set("CLIENT_SECRET", client_secret);
        config.set("TOKEN_URI", token_uri);
        datahub_status::DATAHUB_OK
    })
}

/// Fetch the `jwt-bearer` assertion with client credentials from another provider (an Entra ID
/// app registration, say) and exchange it at the token URI. All three are required.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_assertion_credentials(
    config: *mut datahub_config,
    client_id: *const c_char,
    client_secret: *const c_char,
    token_uri: *const c_char,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        let client_id = ffi_try!(str_arg(client_id, "client_id"));
        let client_secret = ffi_try!(str_arg(client_secret, "client_secret"));
        let token_uri = ffi_try!(str_arg(token_uri, "token_uri"));
        config.set("ASSERTION_CLIENT_ID", client_id);
        config.set("ASSERTION_CLIENT_SECRET", client_secret);
        config.set("ASSERTION_TOKEN_URI", token_uri);
        datahub_status::DATAHUB_OK
    })
}

/// Turn on durable ingest buffering with the default bounds (72 h window, 5 GiB cap, directory
/// `.datahub-spool` under the working directory unless `datahub_config_set_buffer_dir` says
/// otherwise). Off by default.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_enable_buffering(
    config: *mut datahub_config,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        config.set("ENABLE_BUFFERING", "true");
        datahub_status::DATAHUB_OK
    })
}

/// Directory for the on-disk spools. Also enables buffering: a host that names a spool directory
/// wants the spool.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_buffer_dir(
    config: *mut datahub_config,
    dir: *const c_char,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        let dir = ffi_try!(str_arg(dir, "dir"));
        config.set("BUFFER_DIR", dir);
        config.set("ENABLE_BUFFERING", "true");
        datahub_status::DATAHUB_OK
    })
}

/// How long spooled records are kept, in seconds, measured on each record's own timestamp
/// (default 72 h). Also enables buffering.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_buffer_retention_secs(
    config: *mut datahub_config,
    seconds: i64,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        if seconds <= 0 {
            return fail(
                datahub_status::DATAHUB_INVALID_ARGUMENT,
                0,
                "buffer retention must be a positive number of seconds",
            );
        }
        config.set("BUFFER_RETENTION_SECS", &seconds.to_string());
        config.set("ENABLE_BUFFERING", "true");
        datahub_status::DATAHUB_OK
    })
}

/// Size cap for each spool in bytes; the oldest segment is dropped past it (default 5 GiB).
/// Also enables buffering.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_set_buffer_max_bytes(
    config: *mut datahub_config,
    bytes: u64,
) -> datahub_status {
    guard(|| {
        let config = ffi_try!(mut_arg(config, "config"));
        if bytes == 0 {
            return fail(
                datahub_status::DATAHUB_INVALID_ARGUMENT,
                0,
                "buffer size cap must be positive",
            );
        }
        config.set("BUFFER_MAX_BYTES", &bytes.to_string());
        config.set("ENABLE_BUFFERING", "true");
        datahub_status::DATAHUB_OK
    })
}

/// Release a config. The client it was used to build keeps its own copy. NULL is ignored.
#[no_mangle]
pub unsafe extern "C" fn datahub_config_free(config: *mut datahub_config) {
    if !config.is_null() {
        drop(Box::from_raw(config));
    }
}

/// The value of a key, for the rest of the crate.
pub(crate) unsafe fn config_value<'a>(
    config: *const datahub_config,
    key: &str,
) -> Result<Option<&'a str>, datahub_status> {
    Ok(ref_arg(config, "config")?.get(key))
}

#[cfg(test)]
mod tests {
    use super::parse_env_text;

    #[test]
    fn parses_the_dotenv_subset_this_project_uses() {
        let text = "# comment\n\nBASE_URL=https://h\nexport TOKEN='a b'\nSCOPE=\"organization:*\" # tenant\nX = plain # note\nY=\n";
        let entries = parse_env_text(text).unwrap();
        assert_eq!(
            entries,
            vec![
                ("BASE_URL".to_string(), "https://h".to_string()),
                ("TOKEN".to_string(), "a b".to_string()),
                ("SCOPE".to_string(), "organization:*".to_string()),
                ("X".to_string(), "plain".to_string()),
                ("Y".to_string(), String::new()),
            ]
        );
    }

    #[test]
    fn rejects_what_it_cannot_read_and_names_the_line() {
        assert_eq!(
            parse_env_text("A=1\nnot a pair\n").unwrap_err(),
            "line 2: expected KEY=value"
        );
        assert_eq!(
            parse_env_text("BAD KEY=1\n").unwrap_err(),
            "line 1: \"BAD KEY\" is not a valid key"
        );
        assert_eq!(
            parse_env_text("A=\"open\n").unwrap_err(),
            "line 1: unterminated quote"
        );
    }
}
